/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        ink: 'var(--color-ink)',
        'ink-soft': 'var(--color-ink-soft)',
        cream: 'var(--color-cream)',
        sand: 'var(--color-sand)',
        paper: 'var(--color-paper)',
        terracota: 'var(--color-terracota)',
        teal: 'var(--color-teal)',
        amber: 'var(--color-amber)',
        text: 'var(--color-text)',
        'text-muted': 'var(--color-text-muted)',
        'text-inverse': 'var(--color-text-inverse)',
      },
      fontFamily: {
        display: "var(--font-display)",
        body: "var(--font-body)",
        mono: "var(--font-mono)",
      },
      fontSize: {
        hero: ['var(--fs-hero)', { lineHeight: 'var(--lh-hero)' }],
        h1: ['var(--fs-h1)', { lineHeight: 'var(--lh-h1)' }],
        h2: ['var(--fs-h2)', { lineHeight: 'var(--lh-h2)' }],
        h3: ['var(--fs-h3)', { lineHeight: 'var(--lh-h3)' }],
        h4: ['var(--fs-h4)', { lineHeight: 'var(--lh-h4)' }],
        'body-lg': ['var(--fs-body-lg)', { lineHeight: 'var(--lh-body-lg)' }],
        base: ['var(--fs-body)', { lineHeight: 'var(--lh-body)' }],
        meta: ['var(--fs-meta)', { lineHeight: 'var(--lh-meta)' }],
        micro: ['var(--fs-micro)', { lineHeight: 'var(--lh-micro)' }],
      },
      spacing: {
        1: 'var(--space-1)',
        2: 'var(--space-2)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        7: 'var(--space-7)',
        8: 'var(--space-8)',
        9: 'var(--space-9)',
        10: 'var(--space-10)',
        11: 'var(--space-11)',
      },
      borderRadius: {
        none: 'var(--radius-none)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        full: 'var(--radius-pill)',
      },
      boxShadow: {
        card: 'var(--shadow-card)',
        overlay: 'var(--shadow-overlay)',
      },
      screens: {
        sm: 'var(--bp-sm)',
        md: 'var(--bp-md)',
        lg: 'var(--bp-lg)',
        xl: 'var(--bp-xl)',
      },
      maxWidth: {
        container: 'var(--container-max)',
      },
    },
  },
  plugins: [],
};
